# Generated by Django 5.0.6 on 2024-10-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0002_alter_guestaccount_custom_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestaccount',
            name='custom_gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('room_details', models.CharField(max_length=255)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('add_ons', models.JSONField(default=list)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lidoapp.guestaccount')),
            ],
        ),
    ]
