# Generated by Django 5.0.6 on 2024-10-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0003_alter_guestaccount_custom_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='reservation',
            name='gcash_account_name',
            field=models.CharField(default=52, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='gcash_number',
            field=models.CharField(default=522, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='gcash_reference_number',
            field=models.CharField(default=51561, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='overall_total_amount',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_child_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_guest_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='uploaded_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
