# Generated by Django 5.0.6 on 2025-03-31 05:33

import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0003_alter_addon_add_on_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelinfo',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='addon',
            name='add_on_image',
            field=models.ImageField(upload_to=lidoapp.models.get_upload_path, verbose_name='AddOn Image'),
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelinfo',
            name='name',
            field=models.CharField(default='Lido Shores Resort', max_length=255),
        ),
    ]
