# Generated by Django 5.0.6 on 2025-01-29 18:03

import django.db.models.deletion
import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0003_alter_addon_add_on_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='add_on_image',
            field=models.ImageField(upload_to=lidoapp.models.get_upload_path, verbose_name='AddOn Image'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handled_by', models.CharField(max_length=255)),
                ('items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='lidoapp.reservation')),
            ],
        ),
    ]
