# Generated by Django 5.0.6 on 2024-10-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0004_remove_reservation_special_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='gcash_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
