# Generated by Django 5.0.6 on 2025-03-31 05:36

import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0004_remove_hotelinfo_updated_at_alter_addon_add_on_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='add_on_image',
            field=models.ImageField(upload_to=lidoapp.models.get_upload_path, verbose_name='AddOn Image'),
        ),
    ]
