# Generated by Django 5.0.6 on 2025-01-29 18:16

import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0004_alter_addon_add_on_image_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='add_on_image',
            field=models.ImageField(upload_to=lidoapp.models.get_upload_path, verbose_name='AddOn Image'),
        ),
    ]
