# Generated by Django 5.0.6 on 2025-01-29 18:30

import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0005_receipt_receipt_file_alter_addon_add_on_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='add_on_image',
            field=models.ImageField(upload_to=lidoapp.models.get_upload_path, verbose_name='AddOn Image'),
        ),
    ]
