# Generated by Django 5.0.6 on 2024-10-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0005_alter_reservation_gcash_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='add_ons',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
