# Generated by Django 5.0.6 on 2024-10-12 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0006_alter_reservation_add_ons'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
