# Generated by Django 5.0.6 on 2025-02-22 19:20

import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0006_receipt_description_alter_addon_add_on_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='add_on_image',
            field=models.ImageField(upload_to=lidoapp.models.get_upload_path, verbose_name='AddOn Image'),
        ),
    ]
