# Generated by Django 5.0.6 on 2025-02-24 10:22

import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0007_alter_addon_add_on_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dropdown',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_on_name', models.CharField(max_length=255, verbose_name='AddOn Name')),
            ],
        ),
        migrations.AlterField(
            model_name='addon',
            name='add_on_image',
            field=models.ImageField(upload_to=lidoapp.models.get_upload_path, verbose_name='AddOn Image'),
        ),
    ]
