# Generated by Django 5.0.6 on 2024-10-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0007_reservation_reservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=10),
        ),
    ]
