# Generated by Django 5.0.6 on 2024-10-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0008_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_details',
            new_name='room_chosen',
        ),
    ]
