# Generated by Django 5.0.6 on 2024-10-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0011_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='stock_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
