# Generated by Django 5.0.6 on 2024-10-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0012_alter_addon_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('arrival_datetime', models.DateTimeField()),
                ('status_rate', models.CharField(max_length=50)),
                ('cottage_rate', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=20)),
                ('total_guest_count', models.PositiveIntegerField(default=0)),
                ('total_child_count', models.PositiveIntegerField(default=0)),
                ('overall_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
