# Generated by Django 5.0.6 on 2024-10-13 23:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0013_walkinreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinreservation',
            name='walk_in_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
