# Generated by Django 5.0.6 on 2024-10-20 12:14

import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0014_walkinreservation_walk_in_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(choices=[('wifi', 'Wifi Area'), ('pool', 'Swimming Pool'), ('beach', 'Beach Front'), ('spa', 'Spa Service'), ('gym', 'Gym Area'), ('basketball', 'Basketball Court'), ('service', 'Room Services'), ('cafe', 'Cafe'), ('parking', 'Parking Area'), ('smoking', 'Smoking Area')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/other_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveIntegerField(default=lidoapp.models.generate_room_id, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_capacity', models.PositiveIntegerField()),
                ('room_size', models.PositiveIntegerField(help_text='Enter the size in square feet.')),
                ('room_image', models.ImageField(upload_to='rooms/')),
                ('room_amenities', models.ManyToManyField(blank=True, to='lidoapp.amenity')),
                ('room_images', models.ManyToManyField(blank=True, to='lidoapp.roomimage')),
            ],
        ),
    ]
