# Generated by Django 5.0.6 on 2024-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0016_frontdeskaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('twin', 'Twin Bed')], default='queen', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='room',
            name='room_description',
            field=models.TextField(blank=True, help_text="A detailed description of the room's features and layout.", max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=15),
        ),
    ]
