# Generated by Django 5.0.6 on 2024-11-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0017_room_bed_type_room_discount_room_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenity_type',
            field=models.CharField(choices=[('wifi', 'Wifi Area'), ('pool', 'Swimming Pool'), ('beach', 'Beach Front'), ('spa', 'Spa Service'), ('gym', 'Gym Area'), ('basketball', 'Basketball Court'), ('service', 'Room Services'), ('cafe', 'Cafe'), ('parking', 'Parking Area'), ('smoking', 'Smoking Area')], max_length=20, unique=True),
        ),
    ]
