# Generated by Django 5.0.6 on 2024-11-07 09:36

import django.db.models.deletion
import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0018_alter_amenity_amenity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='lidoapp.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(upload_to=lidoapp.models.room_main_image_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_images',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='lidoapp.roomimage'),
        ),
    ]
