# Generated by Django 5.0.6 on 2024-11-07 20:03

import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0019_roomimage_room_alter_room_room_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to=lidoapp.models.room_additional_image_path),
        ),
    ]
