# Generated by Django 5.0.6 on 2024-11-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0020_roomimage_visible_alter_roomimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenity_type',
            field=models.CharField(choices=[('wifi', 'In-Room Wifi'), ('tv', 'Flat Screen TV'), ('ac', 'Air Conditioning'), ('heater', 'Heater'), ('minibar', 'Minibar'), ('coffee_maker', 'Coffee Maker'), ('microwave', 'Microwave'), ('kitchenette', 'Kitchenette'), ('safe', 'In-Room Safe'), ('hairdryer', 'Hair Dryer'), ('bathrobe', 'Bathrobe'), ('slippers', 'Slippers'), ('iron', 'Iron & Ironing Board'), ('toiletries', 'Complimentary Toiletries'), ('desk', 'Work Desk'), ('phone', 'Telephone'), ('balcony', 'Private Balcony'), ('sofa', 'Sofa'), ('dining_area', 'Dining Area'), ('jacuzzi', 'In-Room Jacuzzi'), ('fireplace', 'Fireplace'), ('soundproofing', 'Soundproofing'), ('smart_lighting', 'Smart Lighting'), ('usb_outlets', 'USB Charging Outlets')], max_length=20, unique=True),
        ),
    ]
