# Generated by Django 5.0.6 on 2024-11-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0022_room_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
