# Generated by Django 5.0.6 on 2024-11-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0024_alter_amenity_amenity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenity_type',
            field=models.CharField(choices=[('wifi', 'In-Room Wifi'), ('tv', 'Flat Screen TV'), ('ac', 'Air Conditioning'), ('heater', 'Heater'), ('coffee_maker', 'Coffee Maker'), ('microwave', 'Microwave'), ('kitchenette', 'Kitchenette'), ('toilet', 'Toilet Room'), ('extratoilet', 'Extra Toilet Room'), ('extrabed', 'Extra Bed Room'), ('bathrobe', 'Bathrobe'), ('toiletries', 'Complimentary Toiletries'), ('desk', 'Work Desk'), ('phone', 'Telephone'), ('balcony', 'Private Balcony'), ('sofa', 'Convertable Sofa'), ('dining_area', 'Dining Area'), ('barbeque', 'Outside Barbeque Area'), ('fireplace', 'Fireplace')], max_length=20, unique=True),
        ),
    ]
