# Generated by Django 5.0.6 on 2024-12-06 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0025_alter_amenity_amenity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='gcash_account_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='gcash_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='gcash_reference_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='uploaded_receipt',
        ),
    ]
