# Generated by Django 5.0.6 on 2024-12-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0027_reservation_address1_reservation_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_child_count',
        ),
        migrations.AddField(
            model_name='reservation',
            name='adult_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='children_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_guest_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
