# Generated by Django 5.0.6 on 2024-12-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0028_remove_reservation_total_child_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_guest_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
