# Generated by Django 5.0.6 on 2024-12-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0029_alter_reservation_total_guest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
