# Generated by Django 5.0.6 on 2024-12-09 04:01

import django.utils.timezone
import lidoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0030_guestaccount_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestaccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='guestaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=lidoapp.models.guest_profile_picture_path),
        ),
    ]
