# Generated by Django 5.0.6 on 2024-12-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0031_guestaccount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestaccount',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guestaccount',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='guestaccount',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
