# Generated by Django 5.0.6 on 2024-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0032_guestaccount_address1_guestaccount_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
