# Generated by Django 5.0.6 on 2024-12-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0033_reservation_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='mobile_phone',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='invoice',
        ),
        migrations.AddField(
            model_name='guestaccount',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
