# Generated by Django 5.0.6 on 2024-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0034_rename_mobile_phone_reservation_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestaccount',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
