# Generated by Django 5.0.6 on 2024-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0035_guestaccount_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/%d/'),
        ),
    ]
